language: php
php:
    - 5.6

services:
  - mysql

before_script:
  - openssl genrsa -passout pass:beehappy -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:beehappy -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  - ls -lart var/jwt
  - mysql -e 'create database beehappy;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - mysql -u travis beehappy < var/dump/beehappy-test.sql

script:
  - phpunit -c phpunit.xml

notifications:
  email:
    -  kevin@labesse.me
