language: php
php:
    - 5.6

services:
  - mysql

before_script:
  - openssl genrsa -passout pass:coucou -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:coucou -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  - mysql -e 'create database beehappy;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console fos:user:create --env=test admin admin@domain.tld admin
  - php bin/console fos:user:create --env=test user1 user1@domain.tld userpass
  - php bin/console fos:user:create --env=test user2 user2@domain.tld userpass

script:
  - phpunit -c phpunit.xml

notifications:
  email:
    -  kevin@labesse.me
