language: php
php:
    - 5.6

services:
  - mysql

before_script:
  - openssl genrsa -passout pass:beehappy -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:beehappy -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  - mysql -e 'create database beehappy;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - mysql -u travis beehappy < var/dump/beehappy-test.sql

script:
  - phpunit -c phpunit.xml

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - export REPO=$DOCKER_USER/bee-happy
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:${TRAVIS_COMMIT::8} .
  - docker tag $REPO:${TRAVIS_COMMIT::8} $REPO:$TAG
  - docker tag $REPO:${TRAVIS_COMMIT::8} $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  email:
    -  kevin@labesse.me

env:
  global:
    secure: JcdG3wEBvf1pMQKpsSLf2W3Fisemd/GpI3cf5zR5EbMttXRG8hI6AmhwcgCFP7CuA6qGRsekSRWcAVhrCBjXIy3UFStu+nt7V2E3Fp1BozIXIvyc+hi4wjELryMJZ7V3VBDLukx3Va9TrigRoKnjMF9nGYDVxMJlk+lXB8DsYTniNi6AFDudMgS6+GNE6ooPdBOp+/HY/Sc6YxBg+ml+VXHvE/LhTqt67LzjBEi0ktfUwhfP2agKBLMJI/bnwHAxABZDnwBGAG8MqTtMkBzrU/nKVn2CbT9IoKdkmrF0X2dV5L7bZMZHo54u57jZ02sn+/7zcGRYpx5VqBuMS6ZhXQ0eoP/Pv7V01Vqzpj+4x7Cr6umki8KSfQyJ6oAsk1czVdUlVgUljXccARQ3OAm7zFMN+UYtTebkaoSlLBTSZ7BsENgulA2B6m4ibtvmz+jhOcMUMTGttfdHrevm6x3bdSn6GkEYbtw+8H5+nTV+xWuzk2hgJmT3wUpsrSRAIAZ2TMhsTLPyhmBXcURonDGcTYxcGDPZiWP51bKKbXEWqxVJ/TFl6icPeq6hTHdbbTYIyGfv9QIXprxI+JNbnsrjN0Na4f2KJFo5g9RfFUBY6tA4jV73IRYjIgZFSEr+jAX3uVEYC3LhSghi5K5rE2KRAdYJApmKayRL7F0WRkx7IUk=
