sudo: required

language: php
php:
    - 5.6

services:
  - mysql
  - docker

install:
  - sudo rm -Rf /var/lib/apt/lists/*
  - sudo apt-get update -qq
  - sudo apt-get install -y mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6  # hack because the mysql service above never starts :(

before_script:
  - openssl genrsa -passout pass:beehappy -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:beehappy -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  - mysql -u root -e 'create database beehappy;'
  - mv app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - mysql -u root beehappy < var/dump/beehappy-test.sql

script:
  - phpunit -c phpunit.xml

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - export REPO=$DOCKER_USER/bee-happy
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:${TAG} .
  - docker push $REPO

notifications:
  email:
    -  kevin@labesse.me

env:
  global:
    secure: "i57a3n5vyKavE4s1CUaiZYPp9vFibuxFoKZf36jR+QxObDfuj5CBTVd/nvYdbabik3W9Gp8gX64n4En4doVtb4bCf21/3YdYElyBc6yZxujj2Lk8Qgv+Gw9+cdvcdWIfUuwMqC3/tiYeAR/tPqh0tqaqdVIXYr4TjFn5yr8zwIuzsLsCrhvx31itL0ktGCgUmYJ0VSxZcZud8R/B35L21T4Q20vlnv1Vugdklfeku68ns2O4mLRjzI1ezTtBFX/fx+K8qqOhBbHXa1vGmWtGD97UNqT5SIeoQRiYZcbM9qfvOQdap/DSb34tJExbRU0RzsmbmIgOXyQ2ynJ2LGpXVEwjoQrvkj8BWI6XpR/6kVmvS8WOh4NKpCqd0CPgEHrScyTmFcjSk88WACNk8+XKA2IAgM7UUswsj1md1K0c+M5d6ePNmY+yz5NW7NzCJs06GBzTtiqLNIwCuSVw4ZFvDTqZ6xTpg5iUq6X7VjuS7mi9EmaHpHn3RL8L0BwweUEKMQ7gfh9II+PwWIW0e9IUk7PuiSDYDmV4ZRVaH6daU7FufSUzL6xkIEvP/gPT+AgOPrbbDyjXFYmPzMjJFZ/X69Lfis/+lUE4h8J3xXSNTfPZI8dskJn/5Bk56Y28TbM4AMTU5+aXBZ0TRHecPhI2r0GpbBzMIkzh1U7RlEBx6ic="
