<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Hive;
use CoreBundle\Entity\Type;
use UserBundle\Entity\User;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlertByHiveAndType(Hive $hive, Type $type)
    {
        $qb = $this->createQueryBuilder('a')
                    ->leftJoin('a.hives', 'g')
                    ->where('g = :hive')
                    ->andWhere('a.type = :type')
                    ->setParameters([
                        'hive' => $hive,
                        'type' => $type,
                    ]);

        return $qb->getQuery()->getResult();
    }

    public function queryBuilderMeAlerts(User $user)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.owner = :user')
            ->setParameter('user', $user);

        return $qb;
    }

    public function queryMeAlerts(User $user)
    {
        return $this->queryBuilderMeAlerts($user)->getQuery();
    }
}
