<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Alert;
use CoreBundle\Entity\Hive;
use UserBundle\Entity\User;

/**
 * HistoryNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNotificationLast24Hours(Hive $hive, Alert $alert)
    {
        $qb = $this->createQueryBuilder('h')
                ->select('COUNT(h.id)')
                ->where('h.hive = :hive')
                ->andWhere('h.alert = :alert')
                ->setParameters([
                    'hive' => $hive,
                    'alert' => $alert,
                ]);

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function queryBuilderNotification(User $user)
    {
        $qb = $this->createQueryBuilder('h')
                ->leftJoin('h.hive', 'hi')
                ->where('hi.owner = :user')
                ->setParameter('user', $user);

        return $qb;
    }

    public function queryBuilderNotificationByHive(Hive $hive)
    {
        $qb = $this->createQueryBuilder('h')
            ->where('h.hive = :hive')
            ->setParameter('hive', $hive);

        return $qb;
    }
}
