<?php

namespace CoreBundle\Repository;
use CoreBundle\Entity\Alert;
use CoreBundle\Entity\Hive;

/**
 * HistoryNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNotificationLast24Hours(Hive $hive, Alert $alert)
    {
        $qb = $this->createQueryBuilder('h')
                ->select('COUNT(h.id)')
                ->where('h.hives = :hive')
                ->andWhere('h.alert = :alert')
                ->setParameters([
                    'hive' => $hive,
                    'alert' => $alert,
                ]);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
